module.exports = [
    `Les pizzas à l'ananas devraient-elle rester légales ?`, 
    `Comment imagines-tu les maisons de retraites dans 40 ans ?`, 
    `Plutôt raclette ou fondue ?`, 
    `Quel est le sport le plus chiant à regarder ?`, 
    `Aimerais-tu avoir le pouvoir de lire dans les pensées ?`, 
    `Décris-toi comme une recette de cuisine.`, 
    `Quelle est la chose la plus bizarre que tu aies mangée ?`, 
    `Quel serait le pire animal dans lequel se réincarner ?`, 
    `Imagine ton premier amendement en tant que président·e.`, 
    `À quoi ressemblerait ta Good place (paradis) ? Et ta Bad place (enfer) ?`, 
    `Quelle statistique sur ta vie aimerais-tu consulter après ta mort ?`, 
    `Dans quel univers imaginaire serait-il le pire de vivre ?`, 
    `Que ferais-tu si plus rien n'était interdit pendant une journée ?`, 
    `Raconte une blague nulle.`, 
    `Invente le pire pouvoir de super-héros.`, 
    `T'es-tu déjà fait piégé·e par un poisson d'avril ?`, 
    `Comment s'appelle (ou s'appellerait) ton ordinateur ?`, 
    `Quel est le pire surnom qu'on t'ait déjà donné ?`, 
    `Penses-tu à étiqueter tes bagages dans le train ?`, 
    `Quel est ton bonbon préféré ?`, 
    `As-tu déjà fait un barathon ?`, 
    `Quel est ton secret pour rester jeune ?`, 
    `Si tu étais un PNJ, quel genre de quêtes donnerais-tu aux héros ?`, 
    `Quel est le pire monde fantasy à vivre en tant qu'habitant lambda ?`, 
    `Penses-tu que les combats de Pokémons sont éthiques ?`, 
    `Que ferais-tu en cas d'invasion zombie ?`, 
    `Quelle est ta manière préférée de torturer des Sims ?`, 
    `Dans quel jeu télévisé aurais-tu le plus de chances de gagner ?`, 
    `Penses-tu que tu irais loin dans Koh-Lanta ?`, 
    `Quel est ton slogan ou jingle de pub préféré ?`, 
    `Cite une chanson qui t'insupportes.`, 
    `Si tu devais faire Pékin Express, avec qui irais-tu ?`, 
    `Penses-tu que tu survivrais aux Hunger Games ?`, 
    `Quel est la chose complètement démodée qui te manque le plus ?`, 
    `Jusqu'à quand as-tu continué à croire au Père Noël ?`
]