module.exports = [
    `Cite une chose complètement démodée qui te manque.`,
    `Quelle était ta matière préférée à l'école ?`,
    `Plutôt livre papier ou liseuse électronique ?`, 
    `Cite un jeu vidéo qui te rend nostalgique.`, 
    `Quel est le pire film (ou série) que tu aies jamais vu ?`, 
    `Cite une chose complètement démodée qui te manque.`, 
    `Quelle était ta matière préférée à l'école ?`, 
    `Dans quelle époque historique aurais-tu aimé vivre ?`, 
    `Quelle star aimerais-tu avoir comme meilleur·e ami·e ?`, 
    `Quel film aimerais-tu voir du point de vue d'un autre personnage ?`, 
    `Quel est ton cocktail préféré ?`, 
    `As-tu déjà voyagé seul·e ?`, 
    `Crois-tu aux formes de vie extra-terrestre ?`, 
    `Plutôt coucher ou lever de soleil ?`, 
    `Quel est le jeu-vidéo le plus surcôté ?`, 
    `Que penses-tu de Twitter ?`, 
    `Plutôt café, bar ou boîte de nuit ?`, 
    `Quel aliment ne mangerais-tu pas, même si ta vie en dépendait ?`, 
    `Quelle est ta boisson préférée ?`, 
    `Plutôt thé ou café ?`, 
    `Quel est ton type de cuisine préféré ?`, 
    `Penses-tu que tu pourrais survivre sur une île déserte ?`, 
    `Dans quel univers imaginaire aimerais-tu vivre ?`, 
    `Décris ta maison ou appartement de rêve.`, 
    `Cite quelque chose que tu trouves surcôté.`, 
    `Quel est l'aspect de la célébrité qui pourrait te plaire le plus ?`, 
    `Quel est ton rythme de sommeil habituel ?`, 
    `Quel est ton signe astrologique ?`, 
    `As-tu une région ou ville de France préférée ?`, 
    `Quels sont tes rituels matinaux ?`, 
    `Pratiques-tu un sport ?`, 
    `Quelle est la chose la plus dangereuse que tu aies faite ?`, 
    `Quel est ton parc d'attractions préféré ?`, 
    `Quel est ton moyen de transport favori ?`, 
    `Quel est le pire cadeau que tu aies jamais reçu ?`, 
    `Quelle est la loi que tu as enfreinte le plus souvent dans ta vie ?`, 
    `Si tu pouvais changer de prénom, que choisirais-tu ?`, 
    `Quel dieu de la mythologie grecque te correspond le plus ?`, 
    `Vers quel univers de jeu-vidéo notre monde est-il susceptible d'évoluer ?`, 
    `Quel est le jeu qui t'as le plus enragé ?`, 
    `Quel est ton Pokémon préféré ?`, 
    `Si tu pouvais complètement oublier un jeu pour y rejouer, lequel choisirais-tu ?`, 
    `Quel est ton arme de prédilection dans les jeux ?`, 
    `Si tu étais un personnage de RPG, de quelle classe serais-tu ?`, 
    `Es-tu un ou une mauvaise joueuse ?`, 
    `As-tu déjà fait un escape game ? Quel a été ton préféré ?`, 
    `Quel est le jeu-vidéo qui t'a le plus marqué·e ?`, 
    `Cite une musique dont tu ne pourras jamais te lasser.`, 
    `As-tu un ou une influenceuse préférée ?`, 
    `Quel est le dernier concert/festival auquel tu as assisté ?`, 
    `À quelle Maison appartiens-tu dans Harry Potter ?`, 
    `Lis-tu encore des magazines/journaux ?`, 
    `Cite un film qui mériterait une suite.`, 
    `Cite une série de films qui aurait dû s'arrêter au premier.`, 
    `Quel univers de films/série a le plus de potentiel pour des spin-offs ?`, 
    `Cite une série que tu as binge-watché.`, 
    `Quelle série as-tu longuement hésité à voir mais adoré au final ?`, 
    `Quelle est ta série comique préférée ?`, 
    `Cite une série où il faut perseverer pour vraiment l'apprécier.`, 
    `Es-tu déjà parti·e d'une salle de cinéma en pleine séance ?`, 
    `T'es-tu déjà trompé·e de film au cinéma ?`, 
    `Quel film/série t'as le plus traumantisé·e ?`, 
    `Quel est ton acteur préféré ? Et ton actrice ?`, 
    `Quel est ton film préféré de tous les temps ?`, 
    `Cite un film dont la bande-originale est mémorable.`, 
    `Cite une série populaire que tu as commencé à regarder après tout le monde.`, 
    `Cite un film avec une fin complètement inattendue.`, 
    `Cite un film et une série qui t'a ému·e jusqu'aux larmes.`, 
    `Cite une série qui aurait dû s'arrêter après la première saison.`
]