module.exports = [
    `Quel est le plus beau compliment que l'on t'ait fait ?`, 
    `Quelle est ta devise dans la vie ?`, 
    `Crois-tu aux formes de vie extra-terrestre ?`, 
    `Quelle est l'avancée technologique la plus prometteuse pour toi ?`, 
    `Comment imagines-tu le monde dans 20 ans ?`, 
    `Comment aborder la question de la technologie avec ses enfants ?`, 
    `Si tu en avais la possibilité, ferais-tu un voyage dans l'espace ?`, 
    `Si tu en avais la possibilité, irais-tu vivre sur une autre planète ?`, 
    `Penses-tu que la télévision va disparaître ?`, 
    `Penses-tu pouvoir rester humble si tu devenais célébre ?`, 
    `Crois-tu en la réincarnation ?`, 
    `Si tu devais donner un TED Talk, quel en serait le sujet ?`, 
    `Si tu pouvais poser une seule question à une entité omnisciente, laquelle serait-elle ?`, 
    `Connais-tu ton type de personnalité MBTI ?`, 
    `Quelle est ta citation préférée ?`, 
    `Nomme un projet à court terme, un à moyen et un à long-terme.`, 
    `Y'a-t-il des imprévus qui ont finalement changé ta vie en bien ?`, 
    `Te souviens-tu d'une belle rencontre avec un inconnu ?`, 
    `Quelle est la compétence dont tu es le/la plus fier/fière ?`, 
    `Que ferais-tu si tu n'avais plus besoin de travailler pour vivre ?`, 
    `Qu'est-ce qui t'émeut toujours trop facilement ?`, 
    `Quelle est la qualité la plus importante pour toi chez un·e ami·e ?`, 
    `Qu'est-ce qui devrait être enseigné dans toutes les écoles ?`, 
    `Qu'est-ce qui te remonte le moral à coup sûr ?`, 
    `Raconte une rencontre dans ta vie qui t'a marqué en bien.`, 
    `As-tu déjà réalisé certains de tes rêves ?`, 
    `Raconte une peur que tu as réussi à dépasser.`, 
    `Y'a-t-il un film ou une série qui a changé ta façon de voir le monde ?`, 
    `Quel est ton meilleur souvenir d'enfance ?`, 
    `Résume ton enfance en 3 mots.`, 
    `Est-ce qu'un film/série t'a déjà fait changer ta vision de la vie ?`, 
    `Préféres-tu recevoir 100 000€ immédiatement ou 200€ tous les mois pour toute ta vie ?`
]