module.exports = [
    `As-tu déjà pleuré en finissant un jeu-vidéo ?`, 
    `As-tu déjà dépensé trop d'argent sur un jeu en ligne ?`, 
    `Y'a-t-il un jeu mobile que tu as honte d'assumer ?`, 
    `Quelle est ta peur la plus ridicule ?`, 
    `Quel est ton achat compulsif le plus ridicule ?`, 
    `Quel est l'achat de valeur que tu regrettes le plus ?`, 
    `Raconte une fois où tu t'es ridiculisé·e en public.`, 
    `As-tu déjà passé plus de trois jours sans te laver ?`, 
    `As-tu déjà suivi une mode ridicule quand tu étais plus jeune ?`, 
    `Quelle est ta résolution du Nouvel An qui revient chaque année ?`, 
    `Raconte ton pire entretien d'embauche.`, 
    `T'es-tu déjà fait avoir par une fake news ?`, 
    `Quelle est ton excuse habituelle pour annuler une sortie ?`, 
    `T'es-tu déjà ridiculisé·e dans une autre langue ?`, 
    `Quel est le dernier mensonge que tu aies raconté ?`, 
    `As-tu déjà tenu un blog où tu racontais ta vie ?`, 
    `As-tu déjà été fan d'un groupe de musique que tu n'assumes pas ?`, 
    `As-tu déjà tenu un journal intime ?`, 
    `As-tu déjà eu un accident de la route bêtement ?`, 
    `Quel est le pire pari que tu aies tenu ?`, 
    `Que s'est-il passé lors de ta pire cuite ?`, 
    `Quelle est la chose la plus illégale que tu aies faite ?`, 
    `Quel est l'endroit le plus fou où tu aies fait l'amour ?`, 
    `Si tu devais résumer ta vie sexuelle en un mot, ce serait...`, 
    `Slip, culotte, string, boxer ou autre ?`, 
    `T'es-tu déjà fait chopé·e lors d’un moment très intime avec toi-même ?`, 
    `As-tu re-couché avec un·e de tes exs ?`, 
    `As-tu déjà créé un compte sur un site porno ?`, 
    `Quel est ton dernier achat dans un sex-shop ?`, 
    `As-tu ou aimerais-tu essayer un Love Hôtel ?`, 
    `As-tu ou aimerais-tu essayer un club de strip-tease ?`, 
    `Avec combien de personnes maximum as-tu fait l'amour en même temps ?`, 
    `Quel genre de roleplay sexy pourrait te plaire ?`, 
    `As-tu déjà dépensé de l'argent pour du porno ?`, 
    `As-tu déjà eu un crush sur un personnage imaginaire ?`, 
    `Quelle est la pire phrase de drague qu'on t'ai dite ?`, 
    `Quelle est la pire application de rencontre que tu aies essayée ?`, 
    `Raconte ton pire date.`, 
    `Quel petit détail peut te faire craquer facilement ?`, 
    `Si tu devais résumer ta vie amoureuse en un mot, ce serait...`, 
    `As-tu un crush sur un personne ici présente ?`, 
    `Raconte ton pire râteau.`, 
    `Quels sont tes tue-l'amour ?`, 
    `Qui est ton crush d'acteur ou d'actrice ?`, 
    `As-tu déjà stalké un·e ex sur les réseaux sociaux ?`, 
    `Quelle est ton excuse quand tu n'es finalement pas intéressé·e après un date ?`, 
    `As-tu déjà menti pour écourter un date qui se passait mal ?`, 
    `Penses-tu qu'il est possible d'aimer plusieurs personnes à la fois ?`, 
    `Penses-tu que l'on peut rester ami·e avec un·e ex ?`, 
    `Quel est ton avis sur les applis de rencontres ?`, 
    `Combien de temps a duré ta plus longue relation sérieuse ?`, 
    `As-tu déjà dépensé pour un site ou appli de rencontres ?`, 
    `Es-tu supersticieux·se ?`
]