module.exports = {
    CHANNEL: '🍻-au-baril-barbu',
    MESSAGES: [
        `🌌 C'est quoi votre signe astrologique ? Est-ce qu'il vous correspond ?`,
        `👁 Vous avez déjà fait des rêves lucides ? Il paraît qu'il y a de nombreuses techniques pour les déclencher plus souvent.`,
        `👀 Vous avez déjà fait de la paralysie du sommeil ? C'est terrifiant, je voyais une forme humaine m'observer dans mon lit, et impossible de bouger.`,
        `🐐 Avez-vous déjà entendu parler de la légende du Dahu ?`,
        `Si vous deviez choisir, vous seriez plutôt loup-garou 🐺 ou vampire 🧛‍♂️ ? Pourquoi ?`,
        `🦄 Si vous pouviez adopter n'importe quelle créature de légende, laquelle choisiriez-vous ?`,
        `💀 C'est quoi vos théories sur ce qu'il se passe après la mort ?`,
        `😱 Quelle était la légende qui vous effrayait le plus quand vous étiez gamin ?`,
        `🙈 Quelle est la légende à laquelle vous avez cru beaucoup trop longtemps ?`,
        `⏰ Avez-vous une théorie sur l'impression déjà-vu ? Certains prétendent qu'il s'agit d'un souvenir d'une vie antérieure...`,
        `😨 Comment vous expliquez le fait de pouvoir sentir quand on est observé ?`,
        `😳 Vous connaissez les creepypastas ? Ce sont des légendes urbaines spécifiquement diffusées sur internet. Vous en avez à partager ?`,
        `😱 Quel est le film/série qui vous a le plus effrayé de votre vie ?`,
        `😨 Quelle a été la plus grosse frayeur de votre vie ?`,
        `💀 Avez-vous déjà échappé de peu à la mort ? Vous connaissez les expériences de mort imminente ?`,
        `🧙‍♂️ À choisir, dans quel univers fantastiques aimeriez-vous vivre ?`,
        `🧙‍♀️ Dans un univers médiéval fantastique, quelle serait votre classe de héros (guerrier, mage, moine, archer...) ? `,
        `🌟 Avez-vous déjà eu une chance tellement incroyable que ça ne pouvait pas être une coïncidence ?`,
        `🔮 Quelle discipline occulte aimeriez-vous le plus maîtriser ? Alchimie, astrologie, divination, magie...`,
        `📿 Avez-vous des superstitions ? C'est bête, mais j'ai toujours peur de briser un miroir.`,
        `🦔 En quoi choisiriez-vous d'être ré-incarné ? Je pense qu'un féroce tigre me correspondrait bien.`,
        `🧙‍♀️ Si vous aviez 15 points, comment seraient-ils répartis chez vous ?\nForce : . / 5\nAgilité : . / 5\nIntelligence : . / 5\nVolonté : . / 5\nPerception : . / 5\nCharisme : . / 5`,
        `🧟‍♂️ Quelle serait la créature la plus effrayante si vous la rencontriez ? Personellement, je ne tiens pas à rencontrer des araignées géantes...`,
        `🔮 Avez-vous déjà eu des rêves prémonitoires ?`,
        `❤️ Êtes-vous déjà tombé amoureux d'une personne après avoir rêvé d'elle ?`,
        `🌖 Avez-vous déjà remarqué des changements d'humeur selon les phases de la Lune ?`,
        `⁉️ Quels phénomènes ne pourra-t-on jamais expliquer par la science ?`,
        `💡 Connaissez-vous la signification de certains rêves ? Par exemple rêver qu'on perd ses dents ?`,
        `💡 Pourquoi les mythes et légendes fascinent autant ?`
    ]
}